# Generated by Django 2.1.4 on 2019-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indiaJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=30)),
                ('empexp', models.IntegerField()),
                ('empskills', models.CharField(max_length=30)),
                ('empphone', models.IntegerField()),
            ],
        ),
    ]
