# Generated by Django 2.1.4 on 2019-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='indiaJob1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=30)),
                ('empexp', models.IntegerField()),
                ('empskills', models.CharField(max_length=30)),
                ('empphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='indiaJob2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=30)),
                ('empexp', models.IntegerField()),
                ('empskills', models.CharField(max_length=30)),
                ('empphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='indiaJob3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=30)),
                ('empexp', models.IntegerField()),
                ('empskills', models.CharField(max_length=30)),
                ('empphone', models.IntegerField()),
            ],
        ),
    ]
